[kdcdefaults]
    kdc_listen = 8888
    kdc_tcp_listen = 8888

[realms]
    ETL.LOCAL = {
        database_name = /home/tandat8896-nix/tandat-interview/ETL/infrastructure/kerberos-data/data/principal
        key_stash_file = /home/tandat8896-nix/tandat-interview/ETL/infrastructure/kerberos-data/data/.k5.ETL.LOCAL
        admin_keytab = /home/tandat8896-nix/tandat-interview/ETL/infrastructure/kerberos-data/data/kadm5.keytab
    }
