[libdefaults]
    renew_lifetime = 7d
    forwardable = true
    default_realm = ETL.LOCAL
    dns_lookup_kdc = false
    dns_lookup_realm = false

[realms]
    ETL.LOCAL = {
        kdc = localhost:8888
        admin_server = localhost
    }

[domain_realm]
    localhost = ETL.LOCAL

[dbdefaults]
    database_name = /home/tandat8896-nix/tandat-interview/ETL/infrastructure/kerberos-data/data/principal

[libdefaults]
    udp_preference_limit = 1
