start-kafka:
    @echo "Đang khởi động Node 1 (Sếp)..."
    kafka-server-start.sh infrastructure/.config/server-1.properties > infrastructure/kafka-data/broker-1.log 2>&1 &
    @echo "Đang khởi động Node 2 (Lính)..."
    kafka-server-start.sh infrastructure/.config/server-2.properties > infrastructure/kafka-data/broker-2.log 2>&1 &
    @echo "Cả 2 Node đang chạy ngầm. Log được lưu tại infrastructure/kafka-data/broker-x.log"
    @echo "Để tắt Kafka, hãy chạy: just stop-kafka"

stop-kafka:
    @echo "Đang dẹp tiệm Kafka..."
    -kafka-server-stop.sh
    sleep 5
    -pkill -f kafka-server-start.sh
    @echo "Đã tắt sạch các Node."

start-spark:
    @echo "Đang khởi động Spark Master..."
    spark-class org.apache.spark.deploy.master.Master --host 127.0.0.1 --port 7077 --webui-port 8181 > infrastructure/spark-data/spark-master.log 2>&1 &
    @echo "Đợi master khởi động..."
    sleep 3
    @echo "Đang khởi động Spark Worker..."
    spark-class org.apache.spark.deploy.worker.Worker --webui-port 8182 -d ./infrastructure/spark-data/worker-work spark://127.0.0.1:7077 > infrastructure/spark-data/spark-worker.log 2>&1 &
    @echo "✅ Master UI: http://127.0.0.1:8181 | Worker UI: http://127.0.0.1:8182"

stop-spark:
    @echo "Đang dẹp tiệm Spark..."
    -pkill -f org.apache.spark.deploy.master.Master
    -pkill -f org.apache.spark.deploy.worker.Worker
    -pkill -f pyspark
    @echo "Đã tắt sạch Spark."

start-kdc:
    @echo "Đang khởi động KDC..."
    krb5kdc -n -r ETL.LOCAL -d infrastructure/kerberos-data/data/principal -p 8888 > infrastructure/kerberos-data/logs/krb5kdc.log 2>&1 &
    @echo "✅ KDC đang chạy :8888"

stop-kdc:
    @echo "Đang dẹp tiệm KDC..."
    -pkill -f krb5kdc
    @echo "Đã tắt KDC."

start-zookeeper:
    @echo "Đang khởi động ZooKeeper..."
    zkServer.sh start
    @echo "✅ ZooKeeper đang chạy :2181"

stop-zookeeper:
    @echo "Đang dẹp tiệm ZooKeeper..."
    zkServer.sh stop
    @echo "Đã tắt ZooKeeper."

start-flink:
    @echo "Đang khởi động Flink..."
    WEBUIPORT=8081 start-cluster.sh
    @echo "✅ Flink UI: http://localhost:8081"

stop-flink:
    @echo "Đang dẹp tiệm Flink..."
    stop-cluster.sh
    @echo "Đã tắt Flink."

shell:
    pyspark --master spark://127.0.0.1:7077 --jars $SPARK_KAFKA_JARS --conf spark.executor.extraClassPath=$SPARK_KAFKA_JARS --conf spark.driver.extraClassPath=$SPARK_KAFKA_JARS --conf spark.jars=$SPARK_KAFKA_JARS --conf spark.executor.userClassPathFirst=true --conf spark.driver.userClassPathFirst=true

test:
    kafka-console-producer.sh --bootstrap-server localhost:9092 --topic user-events
