Server {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  keyTab="/home/tandat8896-nix/tandat-interview/ETL/infrastructure/kerberos-data/data/zookeeper.keytab"
  storeKey=true
  useTicketCache=false
  principal="zookeeper/localhost@ETL.LOCAL";
};
