name: Schema Lint

on:
  pull_request:
    paths:
      - 'migrations/**'
      - 'atlas.hcl'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ariga/setup-atlas@v0

      - name: Lint migrations
        run: atlas migrate lint --env local --latest 1
